name: Tag Publishing

on:
  push:
    tags:
      - '*-dev*'
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLICATION_CREDENTIALS: ${{ secrets.PUBLICATION_CREDENTIALS }}
      IS_ACTION: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build
        run: ./gradlew build --info
      - run: ./gradlew checkMavenCentralPublication --info
      - run: ./gradlew publish --info
